server:
  port: ${PORT:8080}
  forward-headers-strategy: framework

spring:
  application:
    name: secure-edtech-backend

  jackson:
    default-property-inclusion: NON_NULL

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

  data:
    mongodb:
      auto-index-creation: false   # 🔥 important: speeds startup

  mongodb:
    uri: ${MONGODB_URI}

  main:
    lazy-initialization: false

management:
  endpoints:
    web:
      exposure:
        include: health,info

  endpoint:
    health:
      show-details: never   # keep simple

securelearn:
  jwt:
    secret: ${JWT_SECRET}
    access-token-expiration: 900000
    refresh-token-expiration: 604800000

  registration:
    public-enabled: true

  risk:
    screenshot-score: 10
    device-limit: 3
    block-threshold: 50

  storage:
    pdf-path: ./tmp/pdf
    video-path: ./tmp/video